### PR TITLE
New updates

### PR DESCRIPTION
**Pull request by abdosaeedelhassan**
1- adding categories permissions in config file
2- adding categories crud (blade files,controller, routes)

### CODE REVIEW

**Comment by rexlManu** [comment]
LGTM!

I will later test it out but the code looks already nice.

Thanks for your constribution.

**Comment by abdosaeedelhassan** [comment]
your welcome.
any plan to use laravel/livewire, i can convert the forms to livewire
components
thank you

**Comment by rexlManu** [comment]
I would totally support a transition to components. That's one of the most missing feature.

**Comment by abdosaeedelhassan** [comment]
Cool, thanks! , next pull request be livewire component

**Pull request merged**
